// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageArrayProto.proto

package com.dinginfo.seamq.protobuf;

public final class MessageArrayProto {
  private MessageArrayProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageArrayProOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dinginfo.seamq.MessageArrayPro)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    java.util.List<com.dinginfo.seamq.protobuf.MessageProto.MessagePro> 
        getMessagesList();
    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    com.dinginfo.seamq.protobuf.MessageProto.MessagePro getMessages(int index);
    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    java.util.List<? extends com.dinginfo.seamq.protobuf.MessageProto.MessageProOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    com.dinginfo.seamq.protobuf.MessageProto.MessageProOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.dinginfo.seamq.MessageArrayPro}
   */
  public static final class MessageArrayPro extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.dinginfo.seamq.MessageArrayPro)
      MessageArrayProOrBuilder {
    // Use MessageArrayPro.newBuilder() to construct.
    private MessageArrayPro(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageArrayPro(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageArrayPro defaultInstance;
    public static MessageArrayPro getDefaultInstance() {
      return defaultInstance;
    }

    public MessageArrayPro getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageArrayPro(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                messages_ = new java.util.ArrayList<com.dinginfo.seamq.protobuf.MessageProto.MessagePro>();
                mutable_bitField0_ |= 0x00000001;
              }
              messages_.add(input.readMessage(com.dinginfo.seamq.protobuf.MessageProto.MessagePro.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dinginfo.seamq.protobuf.MessageArrayProto.internal_static_com_dinginfo_seamq_MessageArrayPro_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dinginfo.seamq.protobuf.MessageArrayProto.internal_static_com_dinginfo_seamq_MessageArrayPro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro.class, com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageArrayPro> PARSER =
        new com.google.protobuf.AbstractParser<MessageArrayPro>() {
      public MessageArrayPro parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageArrayPro(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageArrayPro> getParserForType() {
      return PARSER;
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    private java.util.List<com.dinginfo.seamq.protobuf.MessageProto.MessagePro> messages_;
    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    public java.util.List<com.dinginfo.seamq.protobuf.MessageProto.MessagePro> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    public java.util.List<? extends com.dinginfo.seamq.protobuf.MessageProto.MessageProOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    public com.dinginfo.seamq.protobuf.MessageProto.MessagePro getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
     */
    public com.dinginfo.seamq.protobuf.MessageProto.MessageProOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private void initFields() {
      messages_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dinginfo.seamq.MessageArrayPro}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dinginfo.seamq.MessageArrayPro)
        com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dinginfo.seamq.protobuf.MessageArrayProto.internal_static_com_dinginfo_seamq_MessageArrayPro_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dinginfo.seamq.protobuf.MessageArrayProto.internal_static_com_dinginfo_seamq_MessageArrayPro_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro.class, com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro.Builder.class);
      }

      // Construct using com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessagesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dinginfo.seamq.protobuf.MessageArrayProto.internal_static_com_dinginfo_seamq_MessageArrayPro_descriptor;
      }

      public com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro getDefaultInstanceForType() {
        return com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro.getDefaultInstance();
      }

      public com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro build() {
        com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro buildPartial() {
        com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro result = new com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro(this);
        int from_bitField0_ = bitField0_;
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro) {
          return mergeFrom((com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro other) {
        if (other == com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dinginfo.seamq.protobuf.MessageArrayProto.MessageArrayPro) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.dinginfo.seamq.protobuf.MessageProto.MessagePro> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = new java.util.ArrayList<com.dinginfo.seamq.protobuf.MessageProto.MessagePro>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.dinginfo.seamq.protobuf.MessageProto.MessagePro, com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder, com.dinginfo.seamq.protobuf.MessageProto.MessageProOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public java.util.List<com.dinginfo.seamq.protobuf.MessageProto.MessagePro> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public com.dinginfo.seamq.protobuf.MessageProto.MessagePro getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public Builder setMessages(
          int index, com.dinginfo.seamq.protobuf.MessageProto.MessagePro value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public Builder setMessages(
          int index, com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public Builder addMessages(com.dinginfo.seamq.protobuf.MessageProto.MessagePro value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public Builder addMessages(
          int index, com.dinginfo.seamq.protobuf.MessageProto.MessagePro value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public Builder addMessages(
          com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public Builder addMessages(
          int index, com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends com.dinginfo.seamq.protobuf.MessageProto.MessagePro> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public com.dinginfo.seamq.protobuf.MessageProto.MessageProOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public java.util.List<? extends com.dinginfo.seamq.protobuf.MessageProto.MessageProOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            com.dinginfo.seamq.protobuf.MessageProto.MessagePro.getDefaultInstance());
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, com.dinginfo.seamq.protobuf.MessageProto.MessagePro.getDefaultInstance());
      }
      /**
       * <code>repeated .com.dinginfo.seamq.MessagePro messages = 1;</code>
       */
      public java.util.List<com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dinginfo.seamq.protobuf.MessageProto.MessagePro, com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder, com.dinginfo.seamq.protobuf.MessageProto.MessageProOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dinginfo.seamq.protobuf.MessageProto.MessagePro, com.dinginfo.seamq.protobuf.MessageProto.MessagePro.Builder, com.dinginfo.seamq.protobuf.MessageProto.MessageProOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.dinginfo.seamq.MessageArrayPro)
    }

    static {
      defaultInstance = new MessageArrayPro(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.dinginfo.seamq.MessageArrayPro)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dinginfo_seamq_MessageArrayPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dinginfo_seamq_MessageArrayPro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027MessageArrayProto.proto\022\022com.dinginfo." +
      "seamq\032\022MessageProto.proto\"C\n\017MessageArra" +
      "yPro\0220\n\010messages\030\001 \003(\0132\036.com.dinginfo.se" +
      "amq.MessageProB0\n\033com.dinginfo.seamq.pro" +
      "tobufB\021MessageArrayProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dinginfo.seamq.protobuf.MessageProto.getDescriptor(),
        }, assigner);
    internal_static_com_dinginfo_seamq_MessageArrayPro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dinginfo_seamq_MessageArrayPro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_dinginfo_seamq_MessageArrayPro_descriptor,
        new java.lang.String[] { "Messages", });
    com.dinginfo.seamq.protobuf.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
