// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseProto_2.proto

package com.dinginfo.seamq.protobuf;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResponseProOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dinginfo.seamq.ResponsePro)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serviceName = 1;</code>
     */
    boolean hasServiceName();
    /**
     * <code>optional string serviceName = 1;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>optional string serviceName = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>optional string version = 2;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 2;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 2;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>optional string requestId = 3;</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional string requestId = 3;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>optional string requestId = 3;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>optional string status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional string status = 4;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>optional string status = 4;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>optional string exception = 5;</code>
     */
    boolean hasException();
    /**
     * <code>optional string exception = 5;</code>
     */
    java.lang.String getException();
    /**
     * <code>optional string exception = 5;</code>
     */
    com.google.protobuf.ByteString
        getExceptionBytes();

    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> 
        getFieldsList();
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro getFields(int index);
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    java.util.List<? extends com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> 
        getFieldsOrBuilderList();
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder getFieldsOrBuilder(
        int index);

    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> 
        getAttributesList();
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro getAttributes(int index);
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    int getAttributesCount();
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    java.util.List<? extends com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> 
        getAttributesOrBuilderList();
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder getAttributesOrBuilder(
        int index);

    /**
     * <code>optional bytes data = 8;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 8;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.dinginfo.seamq.ResponsePro}
   */
  public static final class ResponsePro extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.dinginfo.seamq.ResponsePro)
      ResponseProOrBuilder {
    // Use ResponsePro.newBuilder() to construct.
    private ResponsePro(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponsePro(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponsePro defaultInstance;
    public static ResponsePro getDefaultInstance() {
      return defaultInstance;
    }

    public ResponsePro getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponsePro(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serviceName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              version_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              requestId_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              status_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              exception_ = bs;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                fields_ = new java.util.ArrayList<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro>();
                mutable_bitField0_ |= 0x00000020;
              }
              fields_.add(input.readMessage(com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.PARSER, extensionRegistry));
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                attributes_ = new java.util.ArrayList<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro>();
                mutable_bitField0_ |= 0x00000040;
              }
              attributes_.add(input.readMessage(com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.PARSER, extensionRegistry));
              break;
            }
            case 66: {
              bitField0_ |= 0x00000020;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dinginfo.seamq.protobuf.ResponseProto.internal_static_com_dinginfo_seamq_ResponsePro_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dinginfo.seamq.protobuf.ResponseProto.internal_static_com_dinginfo_seamq_ResponsePro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro.class, com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponsePro> PARSER =
        new com.google.protobuf.AbstractParser<ResponsePro>() {
      public ResponsePro parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponsePro(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponsePro> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVICENAME_FIELD_NUMBER = 1;
    private java.lang.Object serviceName_;
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serviceName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private java.lang.Object version_;
    /**
     * <code>optional string version = 2;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string version = 2;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTID_FIELD_NUMBER = 3;
    private java.lang.Object requestId_;
    /**
     * <code>optional string requestId = 3;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string requestId = 3;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private java.lang.Object status_;
    /**
     * <code>optional string status = 4;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string status = 4;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string status = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCEPTION_FIELD_NUMBER = 5;
    private java.lang.Object exception_;
    /**
     * <code>optional string exception = 5;</code>
     */
    public boolean hasException() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string exception = 5;</code>
     */
    public java.lang.String getException() {
      java.lang.Object ref = exception_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exception_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exception = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionBytes() {
      java.lang.Object ref = exception_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exception_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELDS_FIELD_NUMBER = 6;
    private java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> fields_;
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    public java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    public java.util.List<? extends com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> 
        getFieldsOrBuilderList() {
      return fields_;
    }
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
     */
    public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder getFieldsOrBuilder(
        int index) {
      return fields_.get(index);
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 7;
    private java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> attributes_;
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    public java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> getAttributesList() {
      return attributes_;
    }
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    public java.util.List<? extends com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    public int getAttributesCount() {
      return attributes_.size();
    }
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro getAttributes(int index) {
      return attributes_.get(index);
    }
    /**
     * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
     */
    public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }

    public static final int DATA_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 8;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes data = 8;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      serviceName_ = "";
      version_ = "";
      requestId_ = "";
      status_ = "";
      exception_ = "";
      fields_ = java.util.Collections.emptyList();
      attributes_ = java.util.Collections.emptyList();
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVersionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getStatusBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getExceptionBytes());
      }
      for (int i = 0; i < fields_.size(); i++) {
        output.writeMessage(6, fields_.get(i));
      }
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(7, attributes_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(8, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVersionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStatusBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getExceptionBytes());
      }
      for (int i = 0; i < fields_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, fields_.get(i));
      }
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, attributes_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dinginfo.seamq.ResponsePro}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dinginfo.seamq.ResponsePro)
        com.dinginfo.seamq.protobuf.ResponseProto.ResponseProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dinginfo.seamq.protobuf.ResponseProto.internal_static_com_dinginfo_seamq_ResponsePro_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dinginfo.seamq.protobuf.ResponseProto.internal_static_com_dinginfo_seamq_ResponsePro_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro.class, com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro.Builder.class);
      }

      // Construct using com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFieldsFieldBuilder();
          getAttributesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        exception_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          fieldsBuilder_.clear();
        }
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          attributesBuilder_.clear();
        }
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dinginfo.seamq.protobuf.ResponseProto.internal_static_com_dinginfo_seamq_ResponsePro_descriptor;
      }

      public com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro getDefaultInstanceForType() {
        return com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro.getDefaultInstance();
      }

      public com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro build() {
        com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro buildPartial() {
        com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro result = new com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.exception_ = exception_;
        if (fieldsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            fields_ = java.util.Collections.unmodifiableList(fields_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.fields_ = fields_;
        } else {
          result.fields_ = fieldsBuilder_.build();
        }
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro) {
          return mergeFrom((com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro other) {
        if (other == com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000001;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000002;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasRequestId()) {
          bitField0_ |= 0x00000004;
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.hasStatus()) {
          bitField0_ |= 0x00000008;
          status_ = other.status_;
          onChanged();
        }
        if (other.hasException()) {
          bitField0_ |= 0x00000010;
          exception_ = other.exception_;
          onChanged();
        }
        if (fieldsBuilder_ == null) {
          if (!other.fields_.isEmpty()) {
            if (fields_.isEmpty()) {
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureFieldsIsMutable();
              fields_.addAll(other.fields_);
            }
            onChanged();
          }
        } else {
          if (!other.fields_.isEmpty()) {
            if (fieldsBuilder_.isEmpty()) {
              fieldsBuilder_.dispose();
              fieldsBuilder_ = null;
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000020);
              fieldsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFieldsFieldBuilder() : null;
            } else {
              fieldsBuilder_.addAllMessages(other.fields_);
            }
          }
        }
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000040);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dinginfo.seamq.protobuf.ResponseProto.ResponsePro) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serviceName_ = "";
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serviceName = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>optional string version = 2;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string version = 2;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 2;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 2;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 2;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <code>optional string requestId = 3;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 3;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>optional string status = 4;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string status = 4;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            status_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string status = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string status = 4;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 4;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 4;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exception_ = "";
      /**
       * <code>optional string exception = 5;</code>
       */
      public boolean hasException() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public java.lang.String getException() {
        java.lang.Object ref = exception_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exception_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public com.google.protobuf.ByteString
          getExceptionBytes() {
        java.lang.Object ref = exception_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exception_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public Builder setException(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exception_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public Builder clearException() {
        bitField0_ = (bitField0_ & ~0x00000010);
        exception_ = getDefaultInstance().getException();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public Builder setExceptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exception_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> fields_ =
        java.util.Collections.emptyList();
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          fields_ = new java.util.ArrayList<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro>(fields_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> fieldsBuilder_;

      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> getFieldsList() {
        if (fieldsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fields_);
        } else {
          return fieldsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public int getFieldsCount() {
        if (fieldsBuilder_ == null) {
          return fields_.size();
        } else {
          return fieldsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro getFields(int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);
        } else {
          return fieldsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public Builder setFields(
          int index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.set(index, value);
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public Builder setFields(
          int index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public Builder addFields(com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public Builder addFields(
          int index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(index, value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public Builder addFields(
          com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public Builder addFields(
          int index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<? extends com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> values) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fields_);
          onChanged();
        } else {
          fieldsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public Builder clearFields() {
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          fieldsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public Builder removeFields(int index) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.remove(index);
          onChanged();
        } else {
          fieldsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder getFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder getFieldsOrBuilder(
          int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);  } else {
          return fieldsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public java.util.List<? extends com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> 
           getFieldsOrBuilderList() {
        if (fieldsBuilder_ != null) {
          return fieldsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fields_);
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder addFieldsBuilder() {
        return getFieldsFieldBuilder().addBuilder(
            com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.getDefaultInstance());
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder addFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().addBuilder(
            index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.getDefaultInstance());
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro fields = 6;</code>
       */
      public java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder> 
           getFieldsBuilderList() {
        return getFieldsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> 
          getFieldsFieldBuilder() {
        if (fieldsBuilder_ == null) {
          fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder>(
                  fields_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          fields_ = null;
        }
        return fieldsBuilder_;
      }

      private java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          attributes_ = new java.util.ArrayList<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro>(attributes_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> attributesBuilder_;

      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public Builder setAttributes(
          int index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public Builder setAttributes(
          int index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public Builder addAttributes(com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public Builder addAttributes(
          int index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public Builder addAttributes(
          com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public Builder addAttributes(
          int index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public Builder addAllAttributes(
          java.lang.Iterable<? extends com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public java.util.List<? extends com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.getDefaultInstance());
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.getDefaultInstance());
      }
      /**
       * <code>repeated .com.dinginfo.seamq.DataFieldPro attributes = 7;</code>
       */
      public java.util.List<com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldPro.Builder, com.dinginfo.seamq.protobuf.DataFieldProto.DataFieldProOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 8;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes data = 8;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 8;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 8;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000080);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.dinginfo.seamq.ResponsePro)
    }

    static {
      defaultInstance = new ResponsePro(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.dinginfo.seamq.ResponsePro)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dinginfo_seamq_ResponsePro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dinginfo_seamq_ResponsePro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ResponseProto_2.proto\022\022com.dinginfo.se" +
      "amq\032\024DataFieldProto.proto\"\337\001\n\013ResponsePr" +
      "o\022\023\n\013serviceName\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022" +
      "\021\n\trequestId\030\003 \001(\t\022\016\n\006status\030\004 \001(\t\022\021\n\tex" +
      "ception\030\005 \001(\t\0220\n\006fields\030\006 \003(\0132 .com.ding" +
      "info.seamq.DataFieldPro\0224\n\nattributes\030\007 " +
      "\003(\0132 .com.dinginfo.seamq.DataFieldPro\022\014\n" +
      "\004data\030\010 \001(\014B,\n\033com.dinginfo.seamq.protob" +
      "ufB\rResponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dinginfo.seamq.protobuf.DataFieldProto.getDescriptor(),
        }, assigner);
    internal_static_com_dinginfo_seamq_ResponsePro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dinginfo_seamq_ResponsePro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_dinginfo_seamq_ResponsePro_descriptor,
        new java.lang.String[] { "ServiceName", "Version", "RequestId", "Status", "Exception", "Fields", "Attributes", "Data", });
    com.dinginfo.seamq.protobuf.DataFieldProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
